# Generated by Django 4.2 on 2025-01-09 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 9, 16, 9, 48, 64202), verbose_name='Дата выдачи книги'),
        ),
    ]
